### ISSUE TITLE
`/rocket team view all` never returns

### ISSUE THREAD

**Issue by cheukyin699** [ubclaunchpad/rocket2#481]
**Describe the bug**
`/rocket team view all` never returns.

**Expected behavior**
Something should return.

**Additional context**
Issue seems to be a max recursion depth reached issue when copying the arguments into boto3 scan. Here are the logs:

```
Exception in thread Thread-58:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app/controller/command/parser.py", line 65, in handle_app_command
    v = self.commands[s[0]].handle(cmd_txt, user)
  File "/app/app/controller/command/commands/team.py", line 194, in handle
    return self.view_helper(args.team_name)
  File "/app/app/controller/command/commands/team.py", line 284, in view_helper
    members = self.facade.query_or(User, members_list)
  File "/app/db/dynamodb.py", line 261, in query_or
    resp = table.scan(FilterExpression=filter_expr)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/client.py", line 654, in _convert_to_request_dict
    api_params, operation_model, context)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/client.py", line 677, in _emit_api_params
    params=api_params, model=operation_model, context=context)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
 File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/boto3/dynamodb/transform.py", line 27, in copy_dynamodb_params
    return copy.deepcopy(params)
  File "/usr/local/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/local/lib/python3.7/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/local/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/local/lib/python3.7/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
```

For some reason, this isn't an issue for other teams.

**Comment by cheukyin699** [comment]
This seems to be an on-going issue on [the library's end](https://github.com/boto/boto3/issues/1371), where you cannot add more than 119 objects or else it would trigger a max recursion issue.

One way to circumvent would be to manually segment our queries.
